### ISSUE TITLE
Plot without $DISPLAY environment variable

### ISSUE THREAD

**Issue by tommycarstensen** [rajanil/fastStructure#24]
Is it possible to generate plots without having the $DISPLAY environment variable set? I only have a command line interface available. Thanks.

Traceback (most recent call last):
  File "fastStructure/distruct.py", line 169, in <module>
    figure = plot_admixture(admixture, population_indices, population_labels, title)
  File "fastStructure/distruct.py", line 15, in plot_admixture
    figure = plot.figure(figsize=(5,3))
  File "/lustre/scratch113/teams/sandhu/software/lib/python2.7/site-packages/matplotlib/pyplot.py", line 434, in figure
    **kwargs)
  File "/lustre/scratch113/teams/sandhu/software/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/lustre/scratch113/teams/sandhu/software/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/lustre/scratch113/teams/sandhu/software/lib/python2.7/lib-tk/Tkinter.py", line 1764, in **init**
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by tommycarstensen** [comment]
Problem solved via SO:
http://stackoverflow.com/questions/2801882/generating-a-png-with-matplotlib-when-display-is-undefined
