### ISSUE TITLE
error in distruct.py

### ISSUE THREAD

**Issue by ytguojian** [rajanil/fastStructure#38]
Hi,
I got some error in running distruct.py.
[hrajxg@aklppf31 test]$ python ../distruct.py -K 3 --input=testoutput_simple --output=testoutput_simple_distruct.svg
file with population labels is not provided or does not exist ....
creating population labels based on inferred admixture proportions
Traceback (most recent call last):
  File "../distruct.py", line 169, in <module>
    figure = plot_admixture(admixture, population_indices, population_labels, title)
  File "../distruct.py", line 15, in plot_admixture
    figure = plot.figure(figsize=(5,3))
  File "/software/programming/pfr-python2-2.7.13/lib/python2.7/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/software/programming/pfr-python2-2.7.13/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 44, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/software/programming/pfr-python2-2.7.13/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 51, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/software/programming/pfr-python2-2.7.13/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 242, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)
  File "/software/programming/pfr-python2-2.7.13/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 66, in __init__
    super(FigureCanvasQTAggBase, self).__init__(figure=figure)
  File "/software/programming/pfr-python2-2.7.13/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 236, in __init__
    _create_qApp()
  File "/software/programming/pfr-python2-2.7.13/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 144, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable

Whta's  the problem?
Cheers,

**Comment by liudaliang** [comment]
me too

**Comment by liudaliang** [comment]
你检查下命令行的pythony有没有加版本，是python还是python2.7

**Comment by liudaliang** [comment]
python2.7 distruct.py -K 3 --input=testoutput_simple --output=testoutput_simple_distruct.svg

**Comment by Chenglin20170390** [comment]
I solved this problem by adding follow commands in distruct.py
`import matplotlib as mpl`

`mpl.use('Agg')`
