### ISSUE TITLE
Type error when running test data 

### ISSUE THREAD

**Issue by hrivera28** [rajanil/fastStructure#42]
Hello, 
I'm trying to run the test dataset on a cluster and am getting the following error: 

Traceback (most recent call last):
File "/vortexfs1/apps/bio/faststructure-1.0/structure.py", line 178, in <module>
    params['prior'], params['cv'])
  File "fastStructure.pyx", line 101, in fastStructure.infer_variational_parameters
    E = mlhood.marginal_likelihood(G, psi, pi)
TypeError: Argument 'psi' has incorrect type (expected admixprop.AdmixProp, got admixprop.AdmixProp)

I'm just running the code as suggested in the readme with the test data set: 
python structure.py -K 3 --input=test/testdata --output=testoutput_simple --full --seed=100

with the corresponding paths for my machine of course. 

Any ideas what's happening? I haven't been able to find a mention of a similar error elsewhere. 
Thank you!

**Comment by saurav-baral** [comment]
same issue, any fix. I am thinking of shifting to admixture.

**Comment by hrivera28** [comment]
Hey, no I didn't figure it out. Ended up running Structure on an HPC instead.

**Comment by saurav-baral** [comment]
me either. So I shifted to admixture. Do you know of any advantages of using structure over admixture or any disadvantage of admixture?

**Comment by potant** [comment]
Any progress with the TypeError: Argument 'psi' has incorrect type (expected admixprop.AdmixProp, got admixprop.AdmixProp)?????

I am facing the same issue..

**Comment by potant** [comment]
It seems that the problem comes from Cython package. I uninstalled Cython 0.29, installed 0.22, rebuild again and then the test runnings worked

**Comment by qjy543** [comment]
me too
