### ISSUE TITLE
numpy.AxisError: axis 1 is out of bounds for array of dimension 1

### ISSUE THREAD

**Issue by jaberdugoc** [rajanil/fastStructure#60]
Hi¡
I am running faststructure, the faststructure.py run ok, but when I run choose.py throws this error:

Traceback (most recent call last):
  File "../../../../Users/JABC/Downloads/fastStructure/chooseK.py", line 109, in <module>
    bestKs = parse_varQs(files)
  File "../../../../Users/JABC/Downloads/fastStructure/chooseK.py", line 54, in parse_varQs
    Q = Q/utils.insum(Q,[1])
  File "utils.pyx", line 11, in utils.lambda
  File "<__array_function__ internals>", line 6, in apply_over_axes
  File "/Users/JABC/opt/anaconda3/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 495, in apply_over_axes
    res = func(*args)
  File "<__array_function__ internals>", line 6, in sum
  File "/Users/JABC/opt/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2242, in sum
    initial=initial, where=where)
  File "/Users/JABC/opt/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
numpy.AxisError: axis 1 is out of bounds for array of dimension 1

Please, any ideas to correct this error,
Thanks

**Comment by helizabeth1103** [comment]
Hi @jaberdugoc, the same thing is happening to me. Did you ever figure this out? Thanks!
