### ISSUE TITLE
error in distruct.py

### ISSUE THREAD

**Issue by sekhwal** [rajanil/fastStructure#64]
When I try following command, I am getting following error: Please advise to figure-out.

distruct.py -K 6 --input=/scratch/segi-plink-faststructure/segi-faststructure-out 
--output=/scratch/segi-plink-faststructure/segioutput_faststructure_distruct.svg

ERROR:

file with population labels is not provided or does not exist .... 
creating population labels based on inferred admixture proportions
Traceback (most recent call last):
  File "/home/.conda/envs/my_tools_1/bin/distruct.py", line 166, in <module>
    figure = plot_admixture(admixture, population_indices, population_labels, title)
  File "/home/.conda/envs/my_tools_1/bin/distruct.py", line 17, in plot_admixture
    figure = plot.figure(figsize=(5,3))
  File "/home/.conda/envs/my_tools_1/lib/python2.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/home/.conda/envs/my_tools_1/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/.conda/envs/my_tools_1/lib/python2.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figur
e
    window = Tk.Tk(className="matplotlib")
  File "/home/.conda/envs/my_tools_1/lib/python2.7/lib-tk/Tkinter.py", line 1819, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by jikhashkya** [comment]
I'm getting a similar error. It looks like this hasn't been resolved. @rajanil
